set nocompatible
hi Normal guibg=NONE ctermbg=NONE

" set the runtime path to include Vundle and intialize
call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-easy-align'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'altercation/vim-colors-solarized'
Plug 'christoomey/vim-tmux-navigator'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
call plug#end()

"colors
syntax enable
set background=dark
colorscheme solarized
set guifont="Meslo LG S Regular for Powerline"
set linespace=0
"spaces and tabs
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set autoindent
"ui config
set relativenumber "show relative line numbers
set showcmd "show command in bottom bar
set wildmenu "visual autocomplete
set colorcolumn=80

"vim-airline config
let g:airline_powerline_fonts = 1
"let g:airline#extensions#tabline#enabled = 1
"let g:ariline#extensions#tabline#fnamemod = ':t'
"buffer config
set hidden

" escape into normal mode quickly
imap jk <esc>:w<cr>

"new buffer tab
nmap <C-t> :enew<CR>
"new buffer
nmap <C-o> :badd 
"move to next buffer
"nmap <C-f> :bnext<CR>
"move to previous buffer
"nmap <C-d> :bprev<CR>
"close current buffer
nmap <C-x> :bd<CR>
"show all buffers and their status
nmap <C-b><C-l> :ls<CR>

"shortcuts for vim splits
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-h> <C-w><C-h>

nnoremap ; :w<cr>  
nnoremap <silent> <C-w>w :ZoomWin<CR>

"searching
set incsearch "search as characters appear
set hlsearch "highlight matches
nnoremap <leader><space> :nohlsearch<CR>

"git commit text wrapping
au FileType gitcommit set tw=72
"set paste allows pasting from clip board
set pastetoggle=<C-v>

" Turn off highlighting after searching
nnoremap i :noh<cr>i

let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

filetype plugin indent on
" autocmd FileType urdf setlocal shiftwidth=2 tabstop=2
